#Kindling Age common configuration
#Sat Apr 18 15:30:23 AST 2026
blocks.clayPotCapacityMb=2000
blocks.wetClayPotDuration=2400
tools.huntingSpearSmallGameDamageBonus=0.0
tools.huntingSpearSmallGameDamageMultiplier=1.5
